package modules;

/*
 * PanelHome.java
 *
 * Created on 09 April 2008, 11:00
 */



import core.system.LoggingWindow;

/**
 *
 * @author  SWDEV
 */
public class PanelHome extends javax.swing.JPanel {
    
    private static PanelHome instance = null;

    public static PanelHome getInstance() {
        if(instance == null)instance = new PanelHome();
        return instance;
    }
    private PanelHome() {
        initComponents();

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPMK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPMTS = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        btnPMK.setText("Pengendalian Melalui Komputer");
        btnPMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMKActionPerformed(evt);
            }
        });

        jLabel1.setText("Aplikasi Layanan SMS Telepon Seluler Sebagai Pengendali Jarak Jauh");

        jLabel3.setText("Peralatan Listrik Berbasis Komputer");

        btnPMTS.setText("Pengendalian Melalui Telepon Seluler");
        btnPMTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMTSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPMK, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPMTS))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addGap(90, 90, 90)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPMK, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPMTS, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMKActionPerformed
        //  DB.getInstance().update("konfigurasi", "password='" + txtPassword.getText() + "'", "");
        // DB.getInstance().update("konfigurasi", "nomor_hp='" + txtNomorHP.getText() + "'", "");
        // this.setVisible(false);
}//GEN-LAST:event_btnPMKActionPerformed

    private void btnPMTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMTSActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_btnPMTSActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPMK;
    private javax.swing.JButton btnPMTS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    
}
