

/*
 * Pegawai.java
 *
 * Created on 03 April 2008, 14:41
 */



import modules.*;
import modules.inbox.DaftarInbox;
import modules.log.LogPanel;
import modules.outbox.DaftarOutbox;

//import modules.pengendalian.Pengendalian;
//import modules.peralatan.DaftarPeralatan;

/**
 *
 * @author  SWDEV
 */
public class PengendaliJarakJauh extends javax.swing.JPanel {

    /** Creates new form Pegawai */
    private static PengendaliJarakJauh instance = null;

    public static PengendaliJarakJauh getInstance() {
        if (instance == null) {
            instance = new PengendaliJarakJauh();
        }
        return instance;
    }

    private PengendaliJarakJauh() {
        initComponents();
        btnHome.doClick();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnHome = new javax.swing.JToggleButton();
        btnPengendalian = new javax.swing.JToggleButton();
        btnKonfigurasi = new javax.swing.JToggleButton();
        btnInbox = new javax.swing.JToggleButton();
        btnOutbox = new javax.swing.JToggleButton();
        btnLog = new javax.swing.JToggleButton();
        scrollUtama = new javax.swing.JScrollPane();

        jToolBar1.setRollover(true);

        buttonGroup1.add(btnHome);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home.gif"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHome);

        buttonGroup1.add(btnPengendalian);
        btnPengendalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log.gif"))); // NOI18N
        btnPengendalian.setText("Pengendalian");
        btnPengendalian.setFocusable(false);
        btnPengendalian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPengendalian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPengendalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengendalianActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPengendalian);

        buttonGroup1.add(btnKonfigurasi);
        btnKonfigurasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pelanggan.gif"))); // NOI18N
        btnKonfigurasi.setText("Peralatan");
        btnKonfigurasi.setFocusable(false);
        btnKonfigurasi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKonfigurasi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKonfigurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfigurasiActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKonfigurasi);

        buttonGroup1.add(btnInbox);
        btnInbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inbox.gif"))); // NOI18N
        btnInbox.setText("Inbox");
        btnInbox.setFocusable(false);
        btnInbox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInbox.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInboxActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInbox);

        buttonGroup1.add(btnOutbox);
        btnOutbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outbox.gif"))); // NOI18N
        btnOutbox.setText("Outbox");
        btnOutbox.setFocusable(false);
        btnOutbox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOutbox.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOutbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutboxActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOutbox);

        buttonGroup1.add(btnLog);
        btnLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log.gif"))); // NOI18N
        btnLog.setText("Log");
        btnLog.setFocusable(false);
        btnLog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLog.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLog);

        scrollUtama.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void btnKonfigurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfigurasiActionPerformed
        scrollUtama.setViewportView(Peralatan.getInstance());
}//GEN-LAST:event_btnKonfigurasiActionPerformed

    public void setModul(int i) {
        switch (i) {
            case 0:
                btnHome.setSelected(true);
                btnHomeActionPerformed(null);
                break;
            case 1:
                btnKonfigurasi.setSelected(true);
                break;
             case 2:
                btnInbox.setSelected(true);
                btnInboxActionPerformed(null);
                break;
             case 3:
                btnOutbox.setSelected(true);
                btnOutboxActionPerformed(null);
                break;
             case 4:
                btnLog.setSelected(true);
                btnLogActionPerformed(null);
                break;
        }
    }

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        scrollUtama.setViewportView(PanelHome.getInstance());
}//GEN-LAST:event_btnHomeActionPerformed

    private void btnInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInboxActionPerformed
        scrollUtama.setViewportView(DaftarInbox.getInstance());
}//GEN-LAST:event_btnInboxActionPerformed

    private void btnOutboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutboxActionPerformed
        scrollUtama.setViewportView(DaftarOutbox.getInstance());
}//GEN-LAST:event_btnOutboxActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        scrollUtama.setViewportView(LogPanel.getInstance());
}//GEN-LAST:event_btnLogActionPerformed

    private void btnPengendalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengendalianActionPerformed
         scrollUtama.setViewportView(Pengendalian.getInstance());
}//GEN-LAST:event_btnPengendalianActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnHome;
    private javax.swing.JToggleButton btnInbox;
    private javax.swing.JToggleButton btnKonfigurasi;
    private javax.swing.JToggleButton btnLog;
    private javax.swing.JToggleButton btnOutbox;
    private javax.swing.JToggleButton btnPengendalian;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane scrollUtama;
    // End of variables declaration//GEN-END:variables
}
