/*
 * LogPanel.java
 *
 * Created on July 20, 2008, 11:25 PM
 */


import core.system.DB;
import javax.swing.JComboBox;


/**
 *
 * @author  Syarif
 */
public class Pengendalian extends javax.swing.JPanel {

   private static Pengendalian instance = null;

    public static Pengendalian getInstance() {
        if(instance == null)instance = new Pengendalian();
        return instance;
    }
    private String[][] alat;
    private Pengendalian() {
        initComponents();
      
    }


    @Override
    public void setVisible(boolean aFlag) {
        if(aFlag){
        }
    }



    private void hidupkanBerdasarkanComboBox(JComboBox cbo, int i) {
        if(cbo.getSelectedIndex()==0) ControllParport.getInstance().on(i);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        alat1 = new javax.swing.JLabel();
        cboAlat1 = new javax.swing.JComboBox();
        alat2 = new javax.swing.JLabel();
        cboAlat2 = new javax.swing.JComboBox();
        alat3 = new javax.swing.JLabel();
        cboAlat3 = new javax.swing.JComboBox();
        cboAlat6 = new javax.swing.JComboBox();
        alat6 = new javax.swing.JLabel();
        cboAlat5 = new javax.swing.JComboBox();
        cboAlat4 = new javax.swing.JComboBox();
        alat4 = new javax.swing.JLabel();
        alat5 = new javax.swing.JLabel();
        cboAlat9 = new javax.swing.JComboBox();
        alat9 = new javax.swing.JLabel();
        cboAlat8 = new javax.swing.JComboBox();
        cboAlat7 = new javax.swing.JComboBox();
        alat7 = new javax.swing.JLabel();
        alat8 = new javax.swing.JLabel();
        cboAlat12 = new javax.swing.JComboBox();
        alat12 = new javax.swing.JLabel();
        cboAlat11 = new javax.swing.JComboBox();
        cboAlat10 = new javax.swing.JComboBox();
        alat10 = new javax.swing.JLabel();
        alat11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnApply = new javax.swing.JButton();

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        alat1.setText("Alat 1");

        cboAlat1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat1.setSelectedIndex(1);

        alat2.setText("Alat 2");

        cboAlat2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat2.setSelectedIndex(1);

        alat3.setText("Alat 3");

        cboAlat3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat3.setSelectedIndex(1);

        cboAlat6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat6.setSelectedIndex(1);

        alat6.setText("Alat 6");

        cboAlat5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat5.setSelectedIndex(1);

        cboAlat4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat4.setSelectedIndex(1);

        alat4.setText("Alat 4");

        alat5.setText("Alat 5");

        cboAlat9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat9.setSelectedIndex(1);

        alat9.setText("Alat 9");

        cboAlat8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat8.setSelectedIndex(1);

        cboAlat7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat7.setSelectedIndex(1);

        alat7.setText("Alat 7");

        alat8.setText("Alat 8");

        cboAlat12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat12.setSelectedIndex(1);

        alat12.setText("Alat 12");

        cboAlat11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat11.setSelectedIndex(1);

        cboAlat10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidup", "Mati" }));
        cboAlat10.setSelectedIndex(1);

        alat10.setText("Alat 10");

        alat11.setText("Alat 11");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel13.setText("PERALATAN LISTRIK");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setText("STATUS");

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alat8)
                                .addGap(80, 80, 80)
                                .addComponent(cboAlat8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alat7)
                                .addGap(80, 80, 80)
                                .addComponent(cboAlat7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alat6)
                                .addGap(80, 80, 80)
                                .addComponent(cboAlat6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alat5)
                                .addGap(80, 80, 80)
                                .addComponent(cboAlat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alat4)
                                .addGap(80, 80, 80)
                                .addComponent(cboAlat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alat3)
                                .addGap(80, 80, 80)
                                .addComponent(cboAlat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alat2)
                                .addGap(80, 80, 80)
                                .addComponent(cboAlat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alat1)
                                .addGap(80, 80, 80)
                                .addComponent(cboAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnApply, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(alat12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboAlat12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(alat11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboAlat11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(alat10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboAlat10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(alat9)
                                    .addGap(80, 80, 80)
                                    .addComponent(cboAlat9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat1)
                    .addComponent(cboAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat2)
                    .addComponent(cboAlat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat3)
                    .addComponent(cboAlat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat4)
                    .addComponent(cboAlat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat5)
                    .addComponent(cboAlat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat6)
                    .addComponent(cboAlat6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat7)
                    .addComponent(cboAlat7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat8)
                    .addComponent(cboAlat8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat9)
                    .addComponent(cboAlat9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAlat10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alat10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAlat11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alat11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAlat12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alat12))
                .addGap(18, 18, 18)
                .addComponent(btnApply)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pengendalian", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        //matikan dulu semua
        ControllParport.getInstance().matikanSemua();
        hidupkanBerdasarkanComboBox(cboAlat1,1);
        hidupkanBerdasarkanComboBox(cboAlat2,2);
        hidupkanBerdasarkanComboBox(cboAlat3,3);

        hidupkanBerdasarkanComboBox(cboAlat4,4);
        hidupkanBerdasarkanComboBox(cboAlat5,5);
        hidupkanBerdasarkanComboBox(cboAlat6,6);

        hidupkanBerdasarkanComboBox(cboAlat7,7);
        hidupkanBerdasarkanComboBox(cboAlat8,8);
        hidupkanBerdasarkanComboBox(cboAlat9,9);

        hidupkanBerdasarkanComboBox(cboAlat10,10);
        hidupkanBerdasarkanComboBox(cboAlat11,11);
        hidupkanBerdasarkanComboBox(cboAlat12,12);


        //hidupkan per yg dipilih
    }//GEN-LAST:event_btnApplyActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        ambilNama();
    }//GEN-LAST:event_jPanel1ComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alat1;
    private javax.swing.JLabel alat10;
    private javax.swing.JLabel alat11;
    private javax.swing.JLabel alat12;
    private javax.swing.JLabel alat2;
    private javax.swing.JLabel alat3;
    private javax.swing.JLabel alat4;
    private javax.swing.JLabel alat5;
    private javax.swing.JLabel alat6;
    private javax.swing.JLabel alat7;
    private javax.swing.JLabel alat8;
    private javax.swing.JLabel alat9;
    private javax.swing.JButton btnApply;
    private javax.swing.JComboBox cboAlat1;
    private javax.swing.JComboBox cboAlat10;
    private javax.swing.JComboBox cboAlat11;
    private javax.swing.JComboBox cboAlat12;
    private javax.swing.JComboBox cboAlat2;
    private javax.swing.JComboBox cboAlat3;
    private javax.swing.JComboBox cboAlat4;
    private javax.swing.JComboBox cboAlat5;
    private javax.swing.JComboBox cboAlat6;
    private javax.swing.JComboBox cboAlat7;
    private javax.swing.JComboBox cboAlat8;
    private javax.swing.JComboBox cboAlat9;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void ambilNama() {
            alat=DB.getInstance().getDataSet("select alat1,alat2,alat3,alat4,alat5,alat6,alat7,alat8,alat9,alat10,alat11,alat12 from konfigurasi", false);
            alat1.setText(alat[0][0]);
            alat2.setText(alat[0][1]);
            alat3.setText(alat[0][2]);
            alat4.setText(alat[0][3]);
            alat5.setText(alat[0][4]);
            alat6.setText(alat[0][5]);
            alat7.setText(alat[0][6]);
            alat8.setText(alat[0][7]);
            alat9.setText(alat[0][8]);
            alat10.setText(alat[0][9]);
            alat11.setText(alat[0][10]);
            alat12.setText(alat[0][11]);
        
    }
}
