/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Peralatan.java
 *
 * Created on 02 Feb 09, 14:35:50
 */



import core.system.DB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eko SW
 */
public class Peralatan extends javax.swing.JPanel {
    private String[][] alat;

    /** Creates new form Peralatan */
    private static Peralatan instance = null;

    public static Peralatan getInstance() {
        if(instance == null)instance = new Peralatan();
        return instance;
    }
    private Peralatan() {
        initComponents();
    }

    public void ambilNama() {
        alat = DB.getInstance().getDataSet("select alat1,alat2,alat3,alat4,alat5,alat6,alat7,alat8,alat9,alat10,alat11,alat12 from konfigurasi", false);
        txtAlat1.setText(alat[0][0]);
        txtAlat2.setText(alat[0][1]);
        txtAlat3.setText(alat[0][2]);
        txtAlat4.setText(alat[0][3]);
        txtAlat5.setText(alat[0][4]);
        txtAlat6.setText(alat[0][5]);
        txtAlat7.setText(alat[0][6]);
        txtAlat8.setText(alat[0][7]);
        txtAlat9.setText(alat[0][8]);
        txtAlat10.setText(alat[0][9]);
        txtAlat11.setText(alat[0][10]);
        txtAlat12.setText(alat[0][11]);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnSimpanNamaPeralatan = new javax.swing.JButton();
        alat14 = new javax.swing.JLabel();
        txtAlat12 = new javax.swing.JTextField();
        txtAlat11 = new javax.swing.JTextField();
        txtAlat10 = new javax.swing.JTextField();
        txtAlat9 = new javax.swing.JTextField();
        txtAlat8 = new javax.swing.JTextField();
        txtAlat7 = new javax.swing.JTextField();
        txtAlat6 = new javax.swing.JTextField();
        txtAlat5 = new javax.swing.JTextField();
        txtAlat4 = new javax.swing.JTextField();
        txtAlat2 = new javax.swing.JTextField();
        txtAlat1 = new javax.swing.JTextField();
        txtAlat3 = new javax.swing.JTextField();
        alat1 = new javax.swing.JLabel();
        alat2 = new javax.swing.JLabel();
        alat3 = new javax.swing.JLabel();
        alat4 = new javax.swing.JLabel();
        alat5 = new javax.swing.JLabel();
        alat6 = new javax.swing.JLabel();
        alat7 = new javax.swing.JLabel();
        alat8 = new javax.swing.JLabel();
        alat9 = new javax.swing.JLabel();
        alat10 = new javax.swing.JLabel();
        alat13 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        btnSimpanNamaPeralatan.setText("Simpan");
        btnSimpanNamaPeralatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanNamaPeralatanActionPerformed(evt);
            }
        });

        alat14.setText("Alat 12");

        alat1.setText("Alat 1");

        alat2.setText("Alat 2");

        alat3.setText("Alat 3");

        alat4.setText("Alat 4");

        alat5.setText("Alat 5");

        alat6.setText("Alat 6");

        alat7.setText("Alat 7");

        alat8.setText("Alat 8");

        alat9.setText("Alat 9");

        alat10.setText("Alat 10");

        alat13.setText("Alat 11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSimpanNamaPeralatan)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(alat5)
                                        .addGap(6, 6, 6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(alat4)
                                        .addGap(6, 6, 6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(alat3)
                                        .addGap(6, 6, 6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(alat1)
                                        .addGap(6, 6, 6)))
                                .addComponent(alat2)
                                .addComponent(alat6)
                                .addComponent(alat7)
                                .addComponent(alat8)
                                .addComponent(alat9))
                            .addComponent(alat10)
                            .addComponent(alat13)
                            .addComponent(alat14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlat8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlat9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlat10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlat11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlat12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlat4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlat3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlat2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlat6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlat5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlat7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat1)
                    .addComponent(txtAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alat2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat3)
                    .addComponent(txtAlat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alat4)
                    .addComponent(txtAlat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlat6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alat6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlat7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alat7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlat8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alat8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlat9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alat9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlat10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alat10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alat13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAlat11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAlat12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alat14)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alat5)
                            .addComponent(txtAlat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(181, 181, 181)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnSimpanNamaPeralatan)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanNamaPeralatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanNamaPeralatanActionPerformed
        try {
            java.sql.PreparedStatement p = DB.getInstance().getConnection().prepareStatement("update konfigurasi set alat1=?,alat2=?,alat3=?,alat4=?,alat5=?,alat6=?,alat7=?,alat8=?,alat9=?,alat10=?,alat11=?,alat12=?");
            p.setString(1, txtAlat1.getText());
            p.setString(2, txtAlat2.getText());
            p.setString(3, txtAlat3.getText());
            p.setString(4, txtAlat4.getText());
            p.setString(5, txtAlat5.getText());
            p.setString(6, txtAlat6.getText());
            p.setString(7, txtAlat7.getText());
            p.setString(8, txtAlat8.getText());
            p.setString(9, txtAlat9.getText());
            p.setString(10, txtAlat10.getText());
            p.setString(11, txtAlat11.getText());
            p.setString(12, txtAlat12.getText());
            p.executeUpdate();
            JOptionPane.showMessageDialog(this, "Nama peralatan sudah disimpan");
            Pengendalian.getInstance().ambilNama();
        } catch (SQLException ex) {
            Logger.getLogger(Peralatan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanNamaPeralatanActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        ambilNama();
    }//GEN-LAST:event_jPanel1ComponentShown

    @Override
    public void setVisible(boolean aFlag) {
        if(aFlag){
            ambilNama();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alat1;
    private javax.swing.JLabel alat10;
    private javax.swing.JLabel alat13;
    private javax.swing.JLabel alat14;
    private javax.swing.JLabel alat2;
    private javax.swing.JLabel alat3;
    private javax.swing.JLabel alat4;
    private javax.swing.JLabel alat5;
    private javax.swing.JLabel alat6;
    private javax.swing.JLabel alat7;
    private javax.swing.JLabel alat8;
    private javax.swing.JLabel alat9;
    private javax.swing.JButton btnSimpanNamaPeralatan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtAlat1;
    private javax.swing.JTextField txtAlat10;
    private javax.swing.JTextField txtAlat11;
    private javax.swing.JTextField txtAlat12;
    private javax.swing.JTextField txtAlat2;
    private javax.swing.JTextField txtAlat3;
    private javax.swing.JTextField txtAlat4;
    private javax.swing.JTextField txtAlat5;
    private javax.swing.JTextField txtAlat6;
    private javax.swing.JTextField txtAlat7;
    private javax.swing.JTextField txtAlat8;
    private javax.swing.JTextField txtAlat9;
    // End of variables declaration//GEN-END:variables

}
